### ISSUE TITLE
Determine opening-hours

### ISSUE THREAD

**Issue by ligi** [SpcAppsBln/orga#10]
from my gut I would say: 22.4 19:00 - 24.4 19:00 - but open to suggestions

**Comment by thomschlie** [comment]
Why not start the event on friday 1400(UTC+2)?

**Comment by ligi** [comment]
I thought this might collide with work-hours of some participants - but I am open to suggestions. Perhaps we might make this a field in the form for registration to know our crowd. I am available Friday all day ;-)
