### ISSUE TITLE
Mail to github

### ISSUE THREAD

**Issue by ligi** [SpcAppsBln/orga#11]
just got this advertisement from github:

`Want GitHub to sponsor your next event? Submit your request below with information about your event. You can be verbose, it's ok. We like that.`

we need to fill out this form: https://community.github.com/

**Comment by Letty** [comment]
> What kind of sponsorships are you looking for?

Thats a good question, what do we want?

**Comment by ligi** [comment]
octocat stickers ,-)

**Comment by ligi** [comment]
just submitted the form
