### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by ligi** [SpcAppsBln/orga#6]
Reach out to a space-friendly designer to get some nice images / icon / ..

**Comment by XenGi** [comment]
I heard @herzmut does amazing vector art. Maybe he's interested?

**Comment by ligi** [comment]
Note: Important No usage of nasa logo directly - from the docs:

> Are there any restriction on logo use?
> This is an important one - perhaps one of the more important points we must make today. Yes, there are restrictions on use of the NASA logo. You CANNOT use the NASA logo in any way to promote the event.
